<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\MosaicCRM.ObjectMapping\MosaicCRM.ObjectMapping.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="7.4.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftPackageVersion)" />
    </ItemGroup>

</Project>
