<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="$(MicrosoftPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MicrosoftPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(MicrosoftPackageVersion)" />
        <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.27" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\MosaicCRM.AspNetCore\MosaicCRM.AspNetCore.csproj" />
        <ProjectReference Include="..\MosaicCRM.Core\MosaicCRM.Core.csproj" />
        <ProjectReference Include="..\MosaicCRM.Generators.Module\MosaicCRM.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>
</Project>
