<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MicrosoftPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MicrosoftPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftPackageVersion)" />
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\MosaicCRM.Core.DataAccess\MosaicCRM.Core.DataAccess.csproj"/>
        <ProjectReference Include="..\MosaicCRM.Domain\MosaicCRM.Domain.csproj"/>
        <ProjectReference Include="..\MosaicCRM.Generators.Module\MosaicCRM.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
