<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MosaicCRM.Core\MosaicCRM.Core.csproj" />
      <ProjectReference Include="..\MosaicCRM.Security\MosaicCRM.Security.csproj" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\MosaicCRM.Generators.Module\MosaicCRM.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>
</Project>
